# 01-whitelist-extension.conf

# Allow Vite dev internals (DEV ONLY)
SecRule REQUEST_URI "@beginsWith /@vite/" "id:1000100,phase:1,pass,nolog,skipAfter:END_EXT_CHECK"
SecRule REQUEST_URI "@beginsWith /@id/"   "id:1000101,phase:1,pass,nolog,skipAfter:END_EXT_CHECK"
SecRule REQUEST_URI "@beginsWith /src/"   "id:1000102,phase:1,pass,nolog,skipAfter:END_EXT_CHECK"
SecRule REQUEST_URI "@beginsWith /node_modules/" "id:1000103,phase:1,pass,nolog,skipAfter:END_EXT_CHECK"


# Whitelist rules, deny all URI with an extension except for specific allowed ones
SecRule REQUEST_URI "@rx \.(?!html|css|js|mjs|mapwebp|png|jpe?g|gif|svg|ico|woff2?|ttf)([a-zA-Z0-9]+)(?:\?|$)" \
    "id:1000002, \
    phase:1, \
    deny, \
    status:403, \
    log,msg:'Disallowed file extension'"

